### PR TITLE
Upgrade to Java 11 (WIP - PMD 7.0.0 will remove support for this deprecated Rule name usage.)

### PR DESCRIPTION
**Pull request by ghost**
### Please ensure you have completed the following before submitting:
- [X] Ran all tests to ensure existing functionality wasn't broken
- [ ] Ran all quality assurance checks and fixed any new errors or warnings, which include:
* [PMD](https://pmd.github.io/)
* [FindBugs](http://findbugs.sourceforge.net/)
* [Jacoco](http://eclemma.org/jacoco/) code coverage

**Note: you can complete both boxes by running and fixing warnings/errors with** `gradle clean check`
- [ ] Code is [self documenting](https://en.wikipedia.org/wiki/Self-documenting_code) or a short comment when self documenting isn't possible

### CODE REVIEW

**Comment by jscancella** [comment]
Have you tried https://github.com/jscancella/bagging? might be easier than trying to upgrade this old project that seems to no longer be maintained.

**Comment by ghost** [comment]
@jscancella I have not. What a mess. Thanks.

**Comment by jscancella** [comment]
Yeah one of the reasons I created `bagging` was because there were issues discovered with this repo and as I was the main person who maintained bagit-java when I worked at LoC I wanted to continue fixing it.

**Comment by ghost** [comment]
@jscancella do you recommend published artifacts [com.github.jscancella](https://mvnrepository.com/artifact/com.github.jscancella) » [bagging](https://mvnrepository.com/artifact/com.github.jscancella/bagging) » [4.6](https://mvnrepository.com/artifact/com.github.jscancella/bagging/4.6)? I see Maven central has [BagIt Java](https://mvnrepository.com/artifact/gov.loc/bagit) » [5.2.0](https://mvnrepository.com/artifact/gov.loc/bagit/5.2.0).

Is there any documentation describing the transition, differences, and any regressions? More importantly, would you be willing to accept PR for upgrading to Java 11+ and testing with [ePADD](https://github.com/ePADD/epadd/blob/main/lib/bagit-5.0.0-modified.jar)? Still have to reach out to ePADD contributors to determine modifications and reason to not use signed published artifacts. Thank you.

**Comment by jscancella** [comment]
yes, bagging:4.6 is the latest. 
> Is there any documentation describing the transition, differences, and any regressions?

The documentation I created is located at https://github.com/jscancella/bagging#documentation. Pull requests are welcome if you think there is something missing or unclear.
> More importantly, would you be willing to accept PR for upgrading to Java 11+ and testing with [ePADD](https://github.com/ePADD/epadd/blob/main/lib/bagit-5.0.0-modified.jar)?

Not sure what you mean, https://app.circleci.com/pipelines/github/jscancella/bagging/181/workflows/41ef3304-3920-4f18-8e6d-97c958ce00d3 it already is built with java 11 as you can see

> Still have to reach out to ePADD contributors to determine modifications and reason to not use signed published artifacts

Again, not sure what you mean. Maven central requires jars be signed before they are made available

**Comment by ghost** [comment]
@jscancella thanks for some clarification. The README [requirements](https://github.com/jscancella/bagging#requirements) state Java 8 and did not think to venture into the CI to discovery it builds with Java 11 and 17.

Regarding the ePADD project they are using a modified jar file https://github.com/ePADD/epadd/blob/main/lib/bagit-5.0.0-modified.jar. Would be nice to avoid much trial and error by switching to a published artifact. I guess will have to rely on implementation of [specification ](https://datatracker.ietf.org/doc/html/rfc8493) and perform any refactoring to switch to up-to-date BagIt implementation.

**Pull request closed without merging**
