### PR TITLE
#24

### PR DESCRIPTION
**Pull request by heyitsvic**
Added SHA-3 capabilities to the BagIt library.

### CODE REVIEW

**Comment by heyitsvic** [comment]
Unexpected failures occurred, currently working on fixing breakage.

**Comment by ansell** [comment]
In another project I also include bcpkix-jdk15on. 

Also, the latest version is 1.52, which may have bug fixes (without having looked at the release notes at all).

**Comment by ansell** [comment]
Travis actually uses the Gradle build, not the Maven build, which may be why it failed.

**Comment by johnscancella** [comment]
according to the error it can't find the bouncyCastle dependency
> /home/travis/build/LibraryOfCongress/bagit-java/src/main/java/gov/loc/repository/bagit/utilities/MessageDigestHelper.java:16: package org.bouncycastle.jce.provider does not exist
import org.bouncycastle.jce.provider.BouncyCastleProvider;

**Comment by heyitsvic** [comment]
Thank you all for the help. I however, realized that four of the tests fail on windows:
ZipFileSystemTest: testFileSystem
NameValueWriterImplTest: testWrite
ZipBagWriterTest: testOverwrite
ZipBagWriterTest: testWriter

Just thought I would point that out.

**Comment by johnscancella** [comment]
This will become obsolete when pull request #37 is merged in.

**Comment by heyitsvic** [comment]
Ah okay, understood. I will proceed to closing the pull request.

**Comment by heyitsvic** [comment]
Thank you and absolutely!

**Pull request closed without merging**
